package commands

import (
	"errors"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"

	"github.com/facundoolano/blorg/config"
	"github.com/facundoolano/blorg/site"
	"github.com/fsnotify/fsnotify"
)

// Generate and serve the site, rebuilding when the source files change.
func Serve(rootDir string) error {
	config, err := config.LoadDevServer(rootDir)
	if err != nil {
		return err
	}

	if err := rebuild(config); err != nil {
		return err
	}

	// watch for changes in src and layouts, and trigger a rebuild
	watcher, err := setupWatcher(config)
	if err != nil {
		return err
	}
	defer watcher.Close()

	// serve the target dir with a file server
	fs := http.FileServer(HTMLDir{http.Dir("target/")})
	http.Handle("/", http.StripPrefix("/", fs))
	fmt.Println("server listening at http://localhost:4001/")
	http.ListenAndServe(":4001", nil)

	return nil
}

func rebuild(config *config.Config) error {

	site, err := site.Load(*config)
	if err != nil {
		return err
	}

	if err := site.Build(); err != nil {
		return err
	}

	return nil
}

// Tweaks the http file system to construct a server that hides the .html suffix from requests.
// Based on https://stackoverflow.com/a/57281956/993769
type HTMLDir struct {
	d http.Dir
}

func (d HTMLDir) Open(name string) (http.File, error) {
	// Try name as supplied
	f, err := d.d.Open(name)
	if os.IsNotExist(err) {
		// Not found, try with .html
		if f, err := d.d.Open(name + ".html"); err == nil {
			return f, nil
		}
	}
	return f, err
}

func setupWatcher(config *config.Config) (*fsnotify.Watcher, error) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		return nil, err
	}

	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}

				// some events can be received for temporary files, e.g. .#backup files generated by emacs while editing .org
				// when events regarding such files arrive, discard them here instead of triggering a faulty rebuild
				if _, err := os.Stat(event.Name); errors.Is(err, os.ErrNotExist) {
					// FIXME change to log debug
					fmt.Println("ignoring temporary file", event.Name)
					continue
				}
				// chmod events are noisy, ignore them
				if !event.Has(fsnotify.Chmod) {
					continue
				}

				fmt.Printf("\nFile %s changed, triggering rebuild.\n", event.Name)

				// since new nested directories could be triggering this change, and we need to watch those too
				// and since re-watching files is a noop, I just re-add the entire src everytime there's a change
				if err := addAll(watcher, config); err != nil {
					fmt.Println("error:", err)
					return
				}

				if err := rebuild(config); err != nil {
					fmt.Println("error:", err)
					return
				}

			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				fmt.Println("error:", err)
			}
		}
	}()

	err = addAll(watcher, config)

	return watcher, err
}

// Add the layouts and all source directories to the given watcher
func addAll(watcher *fsnotify.Watcher, config *config.Config) error {
	err := watcher.Add(config.LayoutsDir)
	err = watcher.Add(config.DataDir)
	err = watcher.Add(config.IncludesDir)
	// fsnotify watches all files within a dir, but non recursively
	// this walks through the src dir and adds watches for each found directory
	filepath.WalkDir(config.SrcDir, func(path string, entry fs.DirEntry, err error) error {
		if entry.IsDir() {
			watcher.Add(path)
		}
		return nil
	})
	return err
}
